import type { D1Migration } from "@cloudflare/vitest-pool-workers";

// cloudflare:test's `env` is now typed via the global Cloudflare.Env
// namespace (see worker-configuration.d.ts, generated by `wrangler types`)
// rather than a `ProvidedEnv` interface on the "cloudflare:test" module —
// DB/ENVIRONMENT/JWT_SECRET already come from that generated file via
// declaration merging; this just adds the one test-only binding
// (vitest.config.ts's cloudflareTest() bindings) it doesn't know about.
declare global {
  namespace Cloudflare {
    interface Env {
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}
