-- Generated by backend/scripts/generate-seed-migration.mjs from
-- src/utils/mockData.js's MOCK_BOOKS — do not hand-edit; re-run the
-- script instead so this can never drift from the frontend's mock data.

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('1', 'Anansi the Spider', 'Kwame Mensah', 'English', 'Beginner', 12, 'Storybooks', 'Children', 4.8, 3120, 'A clever spider sets out to buy every story in the world from the Sky God himself.', 0, '{"theme":"Folktales & Legends"}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('1', 1, 'Anansi was a clever spider who loved stories. He lived in a great forest where all the animals gathered to share tales.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('1', 2, 'One day, Anansi decided he wanted to own all the stories in the world. He climbed up to where the Sky God lived.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('1', 3, '"Sky God," said Anansi, "I want to buy your stories." The Sky God laughed. "Many kings have tried. What can a small spider offer?"');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('1', 4, '"Name your price," said Anansi boldly. The Sky God thought for a moment. "Bring me Onini the Python, Osebo the Leopard, and the Mmoboro Hornets."');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('1', 5, 'Anansi smiled and set off. He was small, but he was clever — and cleverness was the greatest power of all.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('2', 'Simba na Ndoto Yake', 'Fatuma Njoroge', 'Swahili', 'Beginner', 10, 'Storybooks', 'Children', 4.6, 2430, 'A young lion climbs the tallest mountain on the savanna, chasing a dream to touch the clouds.', 0, '{"theme":"Adventure"}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('2', 1, 'Simba alikuwa simba mdogo aliyeishi kwenye savanna kubwa. Alikuwa na ndoto moja kubwa — kutaka kuruka juu ya mawingu.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('2', 2, 'Kila siku, Simba alitazama angani na kusema, "Siku moja, nitafika huko juu."');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('2', 3, 'Mama yake alimwambia, "Simba, simama imara. Nguvu yako ipo ardhini, si angani."');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('2', 4, 'Lakini Simba hakusikia. Alikimbia, akaruka, akapanda mlima mrefu zaidi kwenye savanna.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('2', 5, 'Alipofika juu ya mlima, aliona wingu moja karibu sana. Akagusa kwa mkono wake. Baridi. Laini. Halisi.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('3', 'Adébáyọ̀ àti Àárọ̀ Tuntun', 'Bisi Adeyemi', 'Yoruba', 'Intermediate', 14, 'Language & Culture', 'Young Adult', 4.4, 1580, 'A gentle morning-in-the-life story following Adébáyọ̀ and his best friend on the walk to school.', 1, '{}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('3', 1, 'Adébáyọ̀ jí ni àárọ̀ kutukutu. Ojú ọ̀run ṣì ń mọ́lẹ̀, ṣùgbọ́n ọkàn rẹ̀ ti jí.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('3', 2, '"Ọjọ́ tuntun, àǹfààní tuntun," ni ìyá rẹ̀ sọ. Adébáyọ̀ rẹ̀rìn-ín.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('3', 3, 'Ó wọ aṣọ rẹ̀, jẹ oúnjẹ àárọ̀ rẹ̀, ó sì gba àpò ìwé rẹ̀. Ọjọ́ ìwé ni lónìí.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('3', 4, 'Ní ọ̀nà, ó pàdé Tunde ọrẹ rẹ̀. "Ṣé o ti ṣe iṣẹ́ inú ìwé?" ni Tunde béèrè.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('3', 5, 'Adébáyọ̀ rẹ̀rìn-ín tí ó sì sọ pé, "Mo ṣe rẹ̀. Jẹ ká lọ." Wọn sáré lọ sí ilé ẹ̀kọ́ papọ̀.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('4', 'UNomvula noMvula', 'Thandi Dlamini', 'Zulu', 'Beginner', 8, 'Science', 'Children', 4.5, 1960, 'A curious girl named after the rain learns how storm clouds gather and why the rain falls.', 1, '{}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('4', 1, 'UNomvula wathanda imvula. Igama lakhe lalitsho lokho — umuntu womvula.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('4', 2, 'Ngelanga elilodwa, izulu laba mnyama. Izintaba zagcwala amafu amnyama njengemvu.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('4', 3, '"Izeza!" wamemeza uNomvula. Wagijima waya ngaphandle. Izitsha zakhe zamdinga.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('4', 4, 'Imvula yawa. Yawa njengemvula enkulu nenethezekile. UNomvula wavula izandla zakhe.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('4', 5, 'Umama wakhe wamemeza ekungeneni. UNomvula wasebenza, wamemeza ukushaya komuntu. Wabuya phakathi, engene ngelisisi.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('5', 'Kouamé et le Baobab Magique', 'Aya Koné', 'French', 'Intermediate', 16, 'Language & Culture', 'Young Adult', 4.9, 2710, 'Beneath the village''s oldest baobab, a boy discovers the tree remembers every story ever told.', 0, '{"theme":"Fantasy"}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('5', 1, 'Kouamé avait sept ans et il habitait près du plus grand baobab du village.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('5', 2, 'Les anciens disaient que l''arbre était magique. Kouamé ne savait pas si c''était vrai.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('5', 3, 'Un matin, il entendit quelque chose. Une voix douce, comme le vent dans les feuilles.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('5', 4, '"Qui es-tu?" chuchota Kouamé. "Je suis aussi vieux que la terre," répondit la voix.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('5', 5, 'Kouamé s''assit au pied du baobab et écouta. L''arbre lui raconta toutes les histoires du monde.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('6', 'The River Sings', 'Aisha Mwangi', 'English', 'Advanced', 24, 'History', 'Student', 4.7, 1340, 'A meditation on memory and oral history, told through three generations of women by the same river.', 1, '{}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('6', 1, 'The river had a name before the village did. Before the first hut was built, before the first fire was lit, the river sang.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('6', 2, 'Amara heard it every morning when she went to collect water. The other girls chattered and laughed, but Amara listened.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('6', 3, '"What does it say?" her grandmother asked one evening, watching Amara''s face.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('6', 4, '"It says something is coming," Amara replied quietly. "Something large and slow and very old."');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('6', 5, 'Her grandmother nodded. She had heard the river say the same thing, seventy years before.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('7', 'Zola and the Star Map', 'Kagiso Molefe', 'English', 'Advanced', 20, 'Science', 'Student', 4.9, 2050, 'Using nothing but her grandfather''s hand-drawn star charts, Zola learns to navigate by the night sky.', 1, '{}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('7', 1, 'Zola''s grandfather kept a leather notebook filled with stars — not photographs, but careful ink drawings of the sky.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('7', 2, '"The sky doesn''t lie," he told her. "Learn to read it, and you will never truly be lost."');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('7', 3, 'She began with the brightest points first: the ones that stayed in the same place all year, patient as old friends.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('7', 4, 'Slowly, the scattered dots became shapes, and the shapes became a map — one older than any road.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('7', 5, 'The night the power went out across the whole village, Zola was the only one who wasn''t afraid of the dark.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('8', 'The Chameleon''s Colours', 'Grace Achieng', 'Swahili', 'Beginner', 9, 'Storybooks', 'Children', 4.6, 2890, 'A picture-book journey through the rainforest with a chameleon who can''t decide what colour to be.', 0, '{"theme":"Nature & Environment"}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('8', 1, 'Deep in the rainforest lived a chameleon who could never quite settle on a colour.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('8', 2, 'On Monday he was leaf-green, on Tuesday bark-brown, and by Wednesday a startled, splashy orange.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('8', 3, 'The other animals teased him: "Pick a colour and keep it!" But the chameleon just smiled his slow smile.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('8', 4, 'One day a hungry hawk circled low, and the chameleon turned the exact grey of the stone he sat on.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('8', 5, '"Maybe," said the chameleon afterward, "not choosing is exactly what saved me."');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('9', 'The Solar System in Hausa', 'Ibrahim Sani', 'Hausa', 'Beginner', 11, 'Space', 'Children', 4.8, 4200, 'A bright, simple tour of the sun and the eight planets that circle it, told in Hausa.', 1, '{"theme":"Space & Astronomy"}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('9', 1, 'Rana babbar tauraruwa ce a tsakiyar sararin samaniya. Duniya da sauran taurari suna kewaye da ita.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('9', 2, 'Duniyarmu ita ce ta uku daga rana. Ita ce kawai duniyar da muka san tana da rai a kanta.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('9', 3, 'Bayan Duniya akwai Mars, ja-ja kuma mai duwatsu. Sannan akwai Jupita, babba fiye da su duka.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('9', 4, 'Kowace duniya tana tafiya a hanyarta, ba tare da karo da wata ba. Wannan ake kira kewaya rana.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('9', 5, 'Idan ka duba sama da dare, za ka iya ganin wasu daga cikin waɗannan taurari suna haske a nesa.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('10', 'Understanding Money in Yoruba', 'Folake Ogunleye', 'Yoruba', 'Beginner', 10, 'Finance', 'Children', 4.7, 3650, 'A gentle first lesson on saving, spending and sharing money, told in Yoruba.', 1, '{"theme":"Money & Saving"}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('10', 1, 'Owó jẹ́ ohun tí a máa ń lò láti ra ohun tí a nílò, bíi oúnjẹ, aṣọ àti ìwé.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('10', 2, 'Nígbà tí a bá rí owó, a lè yàn láti lo díẹ̀, kí a sì fi díẹ̀ pamọ́ sínú àpótí ìfowópamọ́.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('10', 3, 'Fífi owó pamọ́ ń ràn wá lọ́wọ́ láti ra ohun tí ó tóbi jù ní ọjọ́ iwájú.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('10', 4, 'A tún lè fi díẹ̀ nínú owó wa ṣe àwọn ẹlòmíràn tí ó nílò rẹ̀ ju wa lọ.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('10', 5, 'Ọmọdé tí ó kọ́ bí a ṣe ń fi owó ṣe nǹkan dáradára máa ń dàgbà di àgbàlagbà tí ó gbọ́n nípa owó.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('11', 'My First Science Book', 'Dr. Ngozi Eze', 'English', 'Beginner', 12, 'Science', 'Children', 4.9, 3980, 'Simple experiments and big questions about water, air, light and living things.', 1, '{"theme":"General Science"}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('11', 1, 'Science is just a fancy word for asking questions and looking closely for answers.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('11', 2, 'Why is the sky blue? Why do plants need sunlight? Why does ice melt in your hand? Scientists ask questions like these every day.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('11', 3, 'You can be a scientist too. All you need is your eyes, your curiosity, and a notebook to write down what you see.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('11', 4, 'Try this: put a spoon in a glass of water and look at it from the side. Does it look bent? That''s science!');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('11', 5, 'Every big discovery started with someone small enough to say, "I wonder why..."');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('12', 'The Human Body in Igbo', 'Chidinma Okafor', 'Igbo', 'Beginner', 13, 'Health', 'Children', 4.6, 2210, 'A friendly introduction to the heart, lungs, bones and senses, told in Igbo.', 1, '{"theme":"Human Body"}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('12', 1, 'Ahụ́ mmadụ dị ka ụlọ dị egwu nke nwere ọtụtụ ụmụ akụkụ na-arụ ọrụ ọnụ.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('12', 2, 'Obi anyị na-arụ ọrụ ehihie na abalị iji zipụ ọbara gaa akụkụ ahụ niile.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('12', 3, 'Ọgịrịga anyị na-enye anyị ike iguzo ọtọ, gbaa ọsọ, na-egwu egwu.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('12', 4, 'Anya, ntị, imi na ire bụ ihe anyị ji amata ihe dị n''ụwa gburugburu anyị.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('12', 5, 'Ile anya n''ahụ́ gị bụ ụzọ mma isi malite ịghọta otú ị dị ndụ.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('13', 'Animals Around Us', 'Grace Achieng', 'English', 'Beginner', 10, 'Animals', 'Children', 4.7, 1890, 'Meet the birds, insects and small creatures that share your backyard and street.', 1, '{"theme":"Wildlife & Nature"}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('13', 1, 'You don''t need to travel far to meet an animal. Look under a leaf, up in a tree, or along a wall at dusk.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('13', 2, 'A weaver bird builds its nest by tying grass into tight knots — no hands, just a clever beak.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('13', 3, 'Ants that look like they''re wandering are usually following an invisible trail of scent left by their sisters.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('13', 4, 'A gecko''s feet are covered in thousands of tiny hairs that let it walk straight up glass.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('13', 5, 'Every animal you meet is solving the same problem you are: finding food, staying safe, and getting home before dark.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('14', 'The Clever Tortoise', 'Kwame Mensah', 'English', 'Beginner', 9, 'Culture', 'Children', 4.8, 2560, 'An old West African folktale about a slow tortoise who out-thinks every animal in the forest.', 0, '{"theme":"Folktales & Legends"}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('14', 1, 'Long ago, when animals still talked, Tortoise was the slowest runner in the whole forest — and everyone knew it.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('14', 2, 'One dry season, the animals agreed that whoever reached the top of the mountain first would be crowned the wisest.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('14', 3, 'Tortoise didn''t race. Instead, he asked each fast animal for a small favour along the way, and they laughed and agreed.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('14', 4, 'By the time Hare and Leopard reached the top, exhausted from running, Tortoise was already there, sipping water.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('14', 5, '"Speed gets you there first," said Tortoise. "Thinking gets you there at all."');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('15', 'Growing Food', 'Amina Osei', 'English', 'Beginner', 10, 'Agriculture', 'Children', 4.6, 1420, 'From a single seed to a full harvest — how the food on your plate actually grows.', 1, '{"theme":"Farming & Food"}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('15', 1, 'Every meal starts as a seed — a tiny package with everything a plant needs to begin.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('15', 2, 'A seed needs three things to wake up: water, warmth, and a little patience.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('15', 3, 'Some plants, like yam and cassava, grow their food underground, hidden from the sun.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('15', 4, 'Farmers watch the sky as closely as the soil — the right rain at the right time can make or ruin a harvest.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('15', 5, 'The next time you eat a fruit or vegetable, think of the whole journey it took just to reach your plate.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('16', 'How Computers Work', 'Tunde Bakare', 'English', 'Intermediate', 14, 'Technology', 'Young Adult', 4.7, 1980, 'What''s really happening inside the box when you tap, click or type.', 1, '{"theme":"Computers & AI"}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('16', 1, 'A computer doesn''t actually understand words or pictures — it only understands two things: on and off.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('16', 2, 'Every letter you type, every colour on your screen, is really just a very long pattern of 1s and 0s underneath.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('16', 3, 'The processor is like the computer''s brain — it does millions of tiny calculations every single second.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('16', 4, 'When you save a file, the computer is writing that pattern of on/off switches somewhere it can find again later.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('16', 5, 'Artificial intelligence is just a computer that has been shown so many examples, it starts recognizing patterns on its own.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('17', 'Queen of Katsina', 'Halima Yusuf', 'English', 'Intermediate', 14, 'History', 'Young Adult', 4.8, 2100, 'A young queen inherits a troubled throne in the ancient trading city of Katsina, and must learn that real power lies in listening before it lies in command.', 1, '{"theme":"History & Leadership","tagline":"A throne, a market at dawn, and a queen who chose to listen first.","availableLanguages":["English","Hausa","Yoruba"],"funFacts":["A kingdom is a place ruled by a king or queen. It can be big or small.","Katsina was one of the great Hausa trading cities, known for its busy markets over 1,000 years ago.","A council of elders traditionally helped advise a ruler on important decisions.","Caravan routes connected West African kingdoms to traders from across the desert.","A good leader often listens more than they speak — just like Queen Amina."],"learningObjectives":[{"title":"Leadership","description":"Learn how good leaders inspire and protect their people."},{"title":"Nigerian History","description":"Discover the rich history of great African kingdoms."},{"title":"Courage","description":"Be brave and stand up for what is right."},{"title":"Teamwork","description":"Understand the power of working together."},{"title":"Wisdom","description":"Make wise decisions that bring peace and prosperity."}]}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('17', 1, 'When the old king of Katsina died, his daughter Amina was not yet ready to rule — but the throne would not wait for her to feel ready.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('17', 2, 'The elders expected a young queen to sit quietly while men made the decisions. Amina had other plans.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('17', 3, 'She rode out to the market at dawn, before the councillors were even awake, and listened to what traders and farmers actually needed.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('17', 4, 'When a dispute broke out between two caravan leaders over a trade route, Amina settled it not with soldiers, but with a question: "What would keep both your families fed this winter?"');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('17', 5, 'Katsina prospered under her — not because she commanded the loudest, but because she was the last person in the room still listening.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('18', 'The Boy Who Invested', 'Emeka Chukwu', 'English', 'Beginner', 10, 'Finance', 'Children', 4.7, 1870, 'Nine-year-old Chidi turns his weekend market-stall earnings into his first real lesson about saving, patience, and watching small money grow into bigger money.', 1, '{"theme":"Money & Investing","tagline":"One boy, one roasting pan, and the week he learned to make money grow.","availableLanguages":["English","Yoruba","Igbo"],"learningObjectives":[{"title":"Saving vs Spending","description":"Learn the difference between spending, saving, and investing."},{"title":"Patience","description":"Understand how small, regular savings grow over time."},{"title":"Goal Setting","description":"Practice setting a simple savings goal and tracking progress toward it."}]}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('18', 1, 'Chidi sold roasted corn at his mother''s stall every Saturday, and every Saturday he spent every single naira he earned by Sunday night.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('18', 2, 'His uncle noticed and asked him a strange question: "What if you only spent half of what you earned, and grew the other half instead?"');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('18', 3, 'Chidi didn''t understand at first. "Grow money? It''s not a seed." His uncle smiled. "It''s exactly like a seed, if you''re patient."');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('18', 4, 'So Chidi began setting aside a little each week, and his uncle showed him how that little bit could be put to work instead of sitting still.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('18', 5, 'Months later, Chidi looked at what he''d saved and grown — enough to buy his own roasting pan. He hadn''t just earned money. He''d learned how to make it work for him.');

INSERT INTO books (id, title, author, language, level, total_pages, category, age_group, rating, reads, description, is_educational, attributes) VALUES ('19', 'Young Inventors', 'Tobenna Eze', 'English', 'Intermediate', 15, 'Technology', 'Student', 4.9, 2450, 'A team of curious kids turns bottle caps, old motors and recycled wire into working machines — and discovers that every invention starts with a problem worth solving.', 1, '{"theme":"Engineering & Innovation","tagline":"A broken water pump, four friends, and a backyard full of spare parts.","availableLanguages":["English","Swahili"],"learningObjectives":[{"title":"Design Thinking","description":"Learn the basic engineering design cycle: problem, idea, build, test, improve."},{"title":"Resourcefulness","description":"See how simple, everyday materials can be reused to build working machines."},{"title":"Confidence","description":"Build confidence that big inventions usually start as small, imperfect prototypes."}]}');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('19', 1, 'The water pump in Ijeoma''s neighbourhood had been broken for weeks, and every trip to fetch water meant walking twice as far.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('19', 2, '"Someone should fix it," her brother said. Ijeoma looked at him. "Why not us?"');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('19', 3, 'She gathered three friends, a box of spare parts, and an old bicycle wheel, and they got to work in her family''s backyard.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('19', 4, 'Their first attempt didn''t work at all. Their second attempt worked for about six seconds before falling apart. Their third attempt pumped water for real.');
INSERT INTO book_pages (book_id, page_number, content) VALUES ('19', 5, 'It wasn''t a perfect machine. But it was theirs, it worked, and it taught them that inventors aren''t people who never fail — they''re people who keep building anyway.');
